(* Generated by ffconf *)
{$ifndef AVUTIL_AVCONFIG_H}
  {$define AVUTIL_AVCONFIG_H}
  const
    AV_HAVE_BIGENDIAN = False;
    AV_HAVE_FAST_UNALIGNED = True;
    AV_HAVE_INCOMPATIBLE_LIBAV_ABI = False;
{$endif} (* AVUTIL_AVCONFIG_H *)
